openapi: 3.0.0
info:
  title: Backend coding test
  description: Riding app documentation.
  version: 1.0.0

paths: 
  # Utils
  /health:
    get:
      tags:
        - Health
      summary: Check server
      description: Check if server is running.
      responses: 
        '200':
          description: Healthy
  # Rides
  /rides:
    $ref: './rides.yaml#/paths/~1rides'
  /rides/{id}:
    $ref: './rides.yaml#/paths/~1rides~1{id}'

x-tagGroups:
  - name: API
    tags:
      - Ride
  - name: Utils
    tags:
      - Health
